// ============================================================
// BioFresh OS — Mock Data
// Realistic Vietnamese agriculture batch data
// ============================================================

import type { Batch, DashboardMetrics, AIScenario } from "@/types";

export const mockBatches: Batch[] = [
  {
    id: "BF-2026-0801",
    fruitType: "strawberry",
    fruitLabel: "Dalat Strawberry",
    variety: "Mùa hè Nhật Bản (Kaorino)",
    weightKg: 40,
    harvestDate: "2026-08-01",
    location: "Đà Lạt, Lâm Đồng",
    farmName: "Nông trại Phong Lan",
    grade: "B",
    status: "cold_storage",
    seedType: "Giống Nhật nhập khẩu F1",
    ripeness: 78,
    harvestWeather: "Mát, 18°C, sương mù nhẹ",
    treatments: [
      {
        id: "t1",
        type: "quality_check",
        label: "Initial Quality Assessment",
        description: "Kiểm tra độ chín, phân loại kích thước và phát hiện hư hỏng",
        timestamp: "2026-08-01T06:30:00",
        notes: "78% đạt tiêu chuẩn Grade B trở lên",
      },
      {
        id: "t2",
        type: "chitosan_spray",
        label: "Chitosan Coating",
        description: "Phun dung dịch Chitosan 1.5% tạo màng bảo vệ tự nhiên",
        timestamp: "2026-08-01T08:00:00",
        notes: "Chitosan chiết xuất từ vỏ tôm organic",
      },
      {
        id: "t3",
        type: "cold_storage",
        label: "Cold Storage Transfer",
        description: "Bảo quản ở nhiệt độ 2-4°C, độ ẩm 90-95%",
        timestamp: "2026-08-01T10:00:00",
        temperature: 3,
        humidity: 92,
        notes: "Kho lạnh số 3 - Khu vực Đà Lạt",
      },
    ],
    qualityMetrics: {
      freshness: 85,
      color: 82,
      firmness: 78,
      aroma: 88,
      overallScore: 83,
      botrytisDetected: false,
      defectCount: 3,
    },
    estimatedValue: 4800000,
  },
  {
    id: "BF-2026-0802",
    fruitType: "strawberry",
    fruitLabel: "Dalat Strawberry",
    variety: "Hàn Quốc (Seolhyang)",
    weightKg: 65,
    harvestDate: "2026-07-28",
    location: "Đà Lạt, Lâm Đồng",
    farmName: "Hợp tác xã Rau Hoa Đà Lạt",
    grade: "A",
    status: "ready_to_sell",
    seedType: "Giống Hàn Quốc nhập khẩu",
    ripeness: 92,
    harvestWeather: "Nắng nhẹ, 20°C",
    treatments: [
      {
        id: "t4",
        type: "quality_check",
        label: "Quality Check",
        description: "Phân loại kích thước và kiểm tra hình thức",
        timestamp: "2026-07-28T07:00:00",
        notes: "92% đạt Grade A",
      },
      {
        id: "t5",
        type: "chitosan_spray",
        label: "Chitosan Treatment",
        description: "Chitosan coating 2%",
        timestamp: "2026-07-28T09:00:00",
      },
      {
        id: "t6",
        type: "cold_storage",
        label: "Cold Storage",
        description: "Kho lạnh 2°C",
        timestamp: "2026-07-28T11:00:00",
        temperature: 2,
        humidity: 93,
      },
      {
        id: "t7",
        type: "packaging",
        label: "Đóng gói xuất bán",
        description: "Đóng hộp 500g, dán nhãn OCOP",
        timestamp: "2026-08-05T08:00:00",
        notes: "130 hộp x 500g",
      },
    ],
    qualityMetrics: {
      freshness: 92,
      color: 95,
      firmness: 88,
      aroma: 94,
      overallScore: 92,
      botrytisDetected: false,
      defectCount: 1,
    },
    estimatedValue: 13000000,
  },
  {
    id: "BF-2026-0803",
    fruitType: "dragon_fruit",
    fruitLabel: "Red Dragon Fruit",
    variety: "Ruột đỏ H14",
    weightKg: 200,
    harvestDate: "2026-07-25",
    location: "Hàm Thuận Nam, Bình Thuận",
    farmName: "Trang trại Thanh Long Xanh",
    grade: "A",
    status: "processing",
    seedType: "Giống H14 chọn lọc",
    ripeness: 90,
    harvestWeather: "Nắng nóng, 34°C",
    treatments: [
      {
        id: "t8",
        type: "quality_check",
        label: "Kiểm tra sau thu hoạch",
        description: "Phân loại theo kích thước và màu sắc vỏ",
        timestamp: "2026-07-25T05:30:00",
        notes: "Trái đạt chuẩn xuất khẩu 85%",
      },
      {
        id: "t9",
        type: "bio_coating",
        label: "Phủ màng sinh học",
        description: "Phủ sáp ong tự nhiên + nano bạc chống nấm",
        timestamp: "2026-07-25T08:00:00",
        notes: "Kéo dài thời hạn sử dụng 5-7 ngày",
      },
    ],
    qualityMetrics: {
      freshness: 88,
      color: 90,
      firmness: 85,
      aroma: 75,
      overallScore: 85,
      botrytisDetected: false,
      defectCount: 5,
    },
    estimatedValue: 8000000,
  },
  {
    id: "BF-2026-0804",
    fruitType: "mango",
    fruitLabel: "Hoa Loc Mango",
    variety: "Cát Chu Đồng Tháp",
    weightKg: 150,
    harvestDate: "2026-07-20",
    location: "Cao Lãnh, Đồng Tháp",
    farmName: "Vườn xoài Bác Hai",
    grade: "B",
    status: "ready_to_sell",
    seedType: "Giống Cát Chu truyền thống",
    ripeness: 75,
    harvestWeather: "Nắng, 32°C, gió nhẹ",
    treatments: [
      {
        id: "t10",
        type: "quality_check",
        label: "Phân loại kích thước",
        description: "Phân 3 loại: lớn (>400g), vừa (300-400g), nhỏ (<300g)",
        timestamp: "2026-07-20T06:00:00",
        notes: "60% loại lớn, 30% vừa, 10% nhỏ",
      },
      {
        id: "t11",
        type: "cold_storage",
        label: "Kho mát",
        description: "Bảo quản 12-13°C chờ chín đều",
        timestamp: "2026-07-20T10:00:00",
        temperature: 12,
        humidity: 85,
      },
      {
        id: "t12",
        type: "packaging",
        label: "Đóng thùng carton",
        description: "Đóng thùng 10kg, lót xốp PE, dán nhãn",
        timestamp: "2026-07-30T07:00:00",
        notes: "15 thùng x 10kg",
      },
    ],
    qualityMetrics: {
      freshness: 80,
      color: 78,
      firmness: 82,
      aroma: 85,
      overallScore: 81,
      botrytisDetected: false,
      defectCount: 8,
    },
    estimatedValue: 6750000,
  },
  {
    id: "BF-2026-0805",
    fruitType: "avocado",
    fruitLabel: "Dak Lak Avocado",
    variety: "Booth 7 Đắk Lắk",
    weightKg: 120,
    harvestDate: "2026-08-03",
    location: "Buôn Ma Thuột, Đắk Lắk",
    farmName: "Nông trại Tây Nguyên Xanh",
    grade: "A",
    status: "harvested",
    seedType: "Booth 7 ghép gốc",
    ripeness: 65,
    harvestWeather: "Mưa nhẹ, 24°C",
    treatments: [
      {
        id: "t13",
        type: "quality_check",
        label: "Kiểm tra ban đầu",
        description: "Kiểm tra trọng lượng, vết thâm, côn trùng",
        timestamp: "2026-08-03T07:00:00",
        notes: "Chất lượng tốt, ít vết thâm",
      },
    ],
    qualityMetrics: {
      freshness: 95,
      color: 88,
      firmness: 90,
      aroma: 70,
      overallScore: 86,
      botrytisDetected: false,
      defectCount: 2,
    },
    estimatedValue: 9600000,
  },
  {
    id: "BF-2026-0806",
    fruitType: "lychee",
    fruitLabel: "Vải thiều Bắc Giang",
    variety: "Vải thiều Lục Ngạn",
    weightKg: 300,
    harvestDate: "2026-06-15",
    location: "Lục Ngạn, Bắc Giang",
    farmName: "HTX Vải thiều Lục Ngạn",
    grade: "A",
    status: "sold",
    seedType: "Giống vải thiều bản địa",
    ripeness: 95,
    harvestWeather: "Nắng nóng, 36°C",
    treatments: [
      {
        id: "t14",
        type: "quality_check",
        label: "Kiểm tra phân loại",
        description: "Loại bỏ trái nứt, sâu; phân hạng",
        timestamp: "2026-06-15T04:30:00",
        notes: "Thu hoạch sáng sớm để giữ tươi",
      },
      {
        id: "t15",
        type: "cold_storage",
        label: "Xử lý SO2 + kho lạnh",
        description: "Xử lý SO2 nồng độ thấp, bảo quản 4°C",
        timestamp: "2026-06-15T06:00:00",
        temperature: 4,
        humidity: 90,
      },
      {
        id: "t16",
        type: "packaging",
        label: "Đóng gói xuất khẩu",
        description: "Đóng thùng xốp 5kg, dán nhãn xuất khẩu Nhật Bản",
        timestamp: "2026-06-18T08:00:00",
        notes: "60 thùng x 5kg — Đơn hàng AEON Japan",
      },
      {
        id: "t17",
        type: "transport",
        label: "Vận chuyển đường không",
        description: "Air cargo Nội Bài → Narita, container lạnh",
        timestamp: "2026-06-19T22:00:00",
        temperature: 2,
        notes: "Vietnam Airlines Cargo, chuyến VN310",
      },
    ],
    qualityMetrics: {
      freshness: 90,
      color: 92,
      firmness: 85,
      aroma: 93,
      overallScore: 90,
      botrytisDetected: false,
      defectCount: 4,
    },
    estimatedValue: 45000000,
  },
  {
    id: "BF-2026-0807",
    fruitType: "passion_fruit",
    fruitLabel: "Chanh dây Gia Lai",
    variety: "Đài Nông 1",
    weightKg: 80,
    harvestDate: "2026-08-05",
    location: "Pleiku, Gia Lai",
    farmName: "Vườn Chanh Dây Tây Nguyên",
    grade: "B",
    status: "harvested",
    seedType: "Đài Nông 1 (Đài Loan)",
    ripeness: 82,
    harvestWeather: "Mát, 22°C, có mưa",
    treatments: [
      {
        id: "t18",
        type: "quality_check",
        label: "Quality Check",
        description: "Đo Brix (>13%), kiểm tra vỏ nhăn/nứt",
        timestamp: "2026-08-05T06:30:00",
        notes: "Brix trung bình 15.2%, chất lượng tốt",
      },
    ],
    qualityMetrics: {
      freshness: 90,
      color: 80,
      firmness: 75,
      aroma: 92,
      overallScore: 84,
      botrytisDetected: false,
      defectCount: 6,
    },
    estimatedValue: 3200000,
  },
  {
    id: "BF-2026-0808",
    fruitType: "strawberry",
    fruitLabel: "Dâu tây Mộc Châu",
    variety: "Akihime (Chương Mỹ)",
    weightKg: 25,
    harvestDate: "2026-08-06",
    location: "Mộc Châu, Sơn La",
    farmName: "Nông trại Mộc Châu Organic",
    grade: "C",
    status: "processing",
    seedType: "Akihime nhập Nhật",
    ripeness: 70,
    harvestWeather: "Mưa to, 16°C",
    treatments: [
      {
        id: "t19",
        type: "quality_check",
        label: "Kiểm tra ban đầu",
        description: "Kiểm tra hư hỏng do mưa, phát hiện nấm Botrytis",
        timestamp: "2026-08-06T08:00:00",
        notes: "⚠️ Phát hiện 12% trái có dấu hiệu nấm Botrytis cinerea",
      },
    ],
    qualityMetrics: {
      freshness: 65,
      color: 70,
      firmness: 60,
      aroma: 72,
      overallScore: 67,
      botrytisDetected: true,
      defectCount: 15,
    },
    estimatedValue: 1500000,
  },
];

export const mockDashboardMetrics: DashboardMetrics = {
  activeBatches: 6,
  spoilageSaved: 47.5,
  spoilageSavedPercent: 23,
  estimatedProfit: 91850000,
  harvestAlerts: 3,
};

export function getAIScenariosForBatch(batchId: string): AIScenario[] {
  const batch = mockBatches.find((b) => b.id === batchId);
  if (!batch) return [];

  // Special scenarios for strawberry batches (the key use case)
  if (batch.fruitType === "strawberry") {
    return [
      {
        id: "s1",
        title: "Bán chợ đầu mối",
        description: `Bán ngay ${batch.weightKg}kg ${batch.fruitLabel} tại chợ đầu mối Đà Lạt/TP.HCM. Giá dao động 80.000-120.000đ/kg tùy thời điểm.`,
        profitLevel: "low",
        profitLabel: "Thấp",
        riskLevel: "medium",
        riskLabel: "Trung bình",
        estimatedProfit: batch.weightKg * 95000,
        timeline: "Ngay lập tức (1-2 ngày)",
        requirements: [
          "Vận chuyển lạnh đến chợ đầu mối",
          "Chấp nhận giá dao động thị trường",
        ],
        isRecommended: false,
        mascotComment: `Bán chợ đầu mối thì nhanh nhưng lời ít lắm nha! Giá đang bị dội vì mùa dâu rộ, chỉ được ~95.000đ/kg thôi. 😥`,
      },
      {
        id: "s2",
        title: "Gom mẻ sấy thăng hoa OCOP ⭐",
        description: `Lưu kho mát chờ gom đủ 200kg, sau đó sấy thăng hoa (freeze-dry) đóng gói sản phẩm OCOP 4 sao. Tỷ lệ chuyển đổi 1:8 (200kg tươi → 25kg khô). Giá bán 1.500.000-2.000.000đ/kg sấy.`,
        profitLevel: "very_high",
        profitLabel: "Rất Cao",
        riskLevel: "low",
        riskLabel: "Thấp",
        estimatedProfit: batch.weightKg * 280000,
        timeline: "2-3 tuần (chờ gom + sấy)",
        requirements: [
          "Kho lạnh 2-4°C liên tục",
          "Gom đủ 200kg từ nhiều lô",
          "Liên kết đơn vị sấy thăng hoa OCOP",
          "Chi phí sấy ~500.000đ/kg khô",
        ],
        isRecommended: true,
        mascotComment: `🌟 Đây là phương án tuyệt vời! Lô dâu tây này nên đưa vào kho lạnh chờ gom đủ 200kg để sấy thăng hoa, biên lợi nhuận sẽ tăng 100% thay vì bán tươi lúc dội chợ! Sấy thăng hoa giữ nguyên hương vị và dinh dưỡng, sản phẩm OCOP 4 sao bán rất chạy trên Shopee và xuất khẩu!`,
      },
      {
        id: "s3",
        title: "Xử lý màng phủ sinh học → Siêu thị",
        description: `Phủ màng Chitosan nâng cao + đóng hộp 250g-500g bán vào hệ thống siêu thị (Co.opmart, WinMart, AEON). Giá bán 180.000-250.000đ/kg.`,
        profitLevel: "high",
        profitLabel: "Cao",
        riskLevel: "low",
        riskLabel: "Thấp",
        estimatedProfit: batch.weightKg * 195000,
        timeline: "3-5 ngày (xử lý + giao hàng)",
        requirements: [
          "Xử lý màng phủ sinh học qua mạng lưới đối tác",
          "Đóng gói chuẩn siêu thị (barcode, nhãn)",
          "Có hợp đồng với siêu thị",
          "Freshness Passport cho truy xuất",
        ],
        isRecommended: false,
        mascotComment: `Bán siêu thị ổn định và uy tín nè! Giá tốt hơn chợ đầu mối nhiều, nhưng cần đóng gói đẹp và có Freshness Passport. Mình sẽ giúp tạo hồ sơ truy xuất cho lô hàng này! 🏪`,
      },
    ];
  }

  // Generic scenarios for other fruits
  return [
    {
      id: "s1",
      title: "Bán tại chợ đầu mối",
      description: `Bán trực tiếp ${batch.weightKg}kg ${batch.fruitLabel} tại chợ đầu mối gần nhất.`,
      profitLevel: "low",
      profitLabel: "Thấp",
      riskLevel: "medium",
      riskLabel: "Trung bình",
      estimatedProfit: batch.estimatedValue * 0.6,
      timeline: "1-2 ngày",
      requirements: ["Vận chuyển đến chợ", "Chấp nhận giá thị trường"],
      isRecommended: false,
      mascotComment: "Bán chợ nhanh gọn nhưng lợi nhuận hạn chế nha!",
    },
    {
      id: "s2",
      title: "Chế biến sản phẩm giá trị gia tăng ⭐",
      description: `Chế biến ${batch.fruitLabel} thành sản phẩm OCOP (sấy, mứt, nước ép) để tăng giá trị gấp 2-3 lần.`,
      profitLevel: "very_high",
      profitLabel: "Rất Cao",
      riskLevel: "low",
      riskLabel: "Thấp",
      estimatedProfit: batch.estimatedValue * 2.5,
      timeline: "1-3 tuần",
      requirements: [
        "Liên kết cơ sở chế biến",
        "Bảo quản lạnh trong thời gian chờ",
        "Đóng gói chuẩn OCOP",
      ],
      isRecommended: true,
      mascotComment:
        "Chế biến giá trị gia tăng là con đường tốt nhất để tăng thu nhập nha! 🌟",
    },
    {
      id: "s3",
      title: "Bán cho siêu thị / xuất khẩu",
      description: `Đóng gói chuẩn và phân phối qua kênh siêu thị hoặc xuất khẩu ${batch.fruitLabel}.`,
      profitLevel: "high",
      profitLabel: "Cao",
      riskLevel: "low",
      riskLabel: "Thấp",
      estimatedProfit: batch.estimatedValue * 1.5,
      timeline: "3-7 ngày",
      requirements: [
        "Đóng gói chuẩn xuất khẩu/siêu thị",
        "Freshness Passport",
        "Hợp đồng với đối tác",
      ],
      isRecommended: false,
      mascotComment:
        "Kênh siêu thị và xuất khẩu ổn định, uy tín, giá tốt! 🏪",
    },
  ];
}

export const dailyInsights = [
  "Giá dâu tây Đà Lạt đang giảm 15% do vào mùa rộ. Nên ưu tiên sấy thăng hoa hoặc bán siêu thị thay vì chợ đầu mối!",
  "Thanh long ruột đỏ đang được thị trường Nhật ưa chuộng. Cơ hội xuất khẩu tốt nếu đạt GlobalGAP!",
  "Nhiệt độ Đà Lạt dự báo tăng 2°C tuần tới — hãy kiểm tra kho lạnh và tăng tần suất kiểm tra chất lượng.",
  "Lô vải thiều Lục Ngạn vừa xuất khẩu thành công sang Nhật. Hợp tác xã nên ghi nhận quy trình để nhân rộng!",
  "Mẹo: Phun Chitosan trong 6 giờ đầu sau thu hoạch giúp kéo dài thời hạn sử dụng thêm 3-5 ngày.",
];
